const APP_KEY='dd_v3_state';
const SESSION_KEY='dd_v3_session';
const DEFAULT_PIN='1612';
const CATS={Courses:'🛒',Repas:'🍽️',Transport:'🚇',Études:'📚',Loisirs:'🎬',Divers:'🧾'};
const REACTIONS=['🔥','👏','❤️'];
const fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n||0));
const safePhone=s=>(s||'').replace(/\D/g,'');
const today=()=>new Date().toISOString().slice(0,10);
const ym=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const monthName=k=>{const [y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1));};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function blankState(){return{profiles:{},expenses:[],messages:{},photos:[],reactions:[]}}
function load(){
  try{
    const v3=JSON.parse(localStorage.getItem(APP_KEY)||'null');
    if(v3)return v3;
    const old=JSON.parse(localStorage.getItem('dd_v2_state')||'null');
    if(old){
      const migrated={...blankState(),profiles:old.profiles||{},expenses:old.expenses||[],messages:old.messages||{}};
      localStorage.setItem(APP_KEY,JSON.stringify(migrated));
      return migrated;
    }
    return blankState();
  }catch{return blankState()}
}
function save(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
let state=load();
let session=JSON.parse(localStorage.getItem(SESSION_KEY)||localStorage.getItem('dd_v2_session')||'null');
if(session && !localStorage.getItem(SESSION_KEY)) localStorage.setItem(SESSION_KEY,JSON.stringify(session));
let view='home';
function me(){return session?state.profiles[session.phone]:null}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
function persistSession(phone){session={phone};localStorage.setItem(SESSION_KEY,JSON.stringify(session))}
function logout(){localStorage.removeItem(SESSION_KEY);session=null;app()}
function app(){if(!session||!me())return renderLogin();if(me().mustChangePin)return renderChangePin(true);renderShell()}

function renderLogin(){document.getElementById('app').innerHTML=`<div class="auth"><div class="auth-card"><img class="auth-icon" src="./dauphine-icon-180.png" alt="Dauphine"><h1>Dépenses Dauphine</h1><p>Dépenses, messages et photo du jour en famille.</p><form id="login" class="form"><div class="field"><label>Numéro de téléphone</label><input id="phone" inputmode="tel" autocomplete="tel" placeholder="06 00 00 00 00" required></div><div class="field"><label>Code à 4 chiffres</label><input id="pin" class="pin" inputmode="numeric" maxlength="4" pattern="[0-9]{4}" placeholder="••••" required></div><button class="btn btn-primary btn-block">Se connecter</button></form><p>Premier accès : code <b>1612</b>. L'application mémorise ensuite ce compte sur cet appareil.</p></div></div>`;
 document.getElementById('login').onsubmit=e=>{e.preventDefault();const phone=safePhone(document.getElementById('phone').value),pin=document.getElementById('pin').value;if(phone.length<10)return toast('Numéro invalide');let p=state.profiles[phone];if(!p){if(pin!==DEFAULT_PIN)return toast('Premier accès : utilisez 1612');const role=confirm('Ce compte est-il celui de l’étudiant ?\nOK = Étudiant / Annuler = Parent')?'student':'parent';let name=prompt('Prénom de ce profil ?')|| (role==='student'?'Yoni':'Parent');p={phone,pin:DEFAULT_PIN,role,name:name.trim(),mustChangePin:true,createdAt:new Date().toISOString()};state.profiles[phone]=p;save()}else if(p.pin!==pin)return toast('Code incorrect');persistSession(phone);app()};}
function renderChangePin(first=false){const p=me();document.getElementById('app').innerHTML=`<div class="auth"><div class="auth-card"><img class="auth-icon" src="./dauphine-icon-180.png"><h1>${first?'Choisissez votre code':'Modifier le code'}</h1><p>Votre code personnel remplace définitivement 1612 pour ce profil.</p><form id="chg" class="form"><div class="field"><label>Nouveau code</label><input id="p1" class="pin" inputmode="numeric" maxlength="4" pattern="[0-9]{4}" required></div><div class="field"><label>Confirmer</label><input id="p2" class="pin" inputmode="numeric" maxlength="4" pattern="[0-9]{4}" required></div><button class="btn btn-primary btn-block">Enregistrer</button></form></div></div>`;document.getElementById('chg').onsubmit=e=>{e.preventDefault();const a=p1.value,b=p2.value;if(!/^\d{4}$/.test(a)||a!==b)return toast('Codes différents');if(a===DEFAULT_PIN)return toast('Choisissez un code différent de 1612');p.pin=a;p.mustChangePin=false;save();toast('Code enregistré');setTimeout(app,250)}}
function renderShell(){const p=me();document.getElementById('app').innerHTML=`<div class="shell"><header class="header"><div class="headrow"><div class="brand"><img src="./dauphine-icon-180.png"><div><small>DÉPENSES DAUPHINE</small><strong>${esc(p.name)}</strong></div></div><div class="pill">${p.role==='student'?'Étudiant':'Parent'}</div></div></header><main id="main" class="container"></main><nav class="tabs"><button class="tab ${view==='home'?'active':''}" data-v="home"><b>⌂</b>Accueil</button><button class="tab ${view==='photo'?'active':''}" data-v="photo"><b>📷</b>Photo</button><button class="tab ${view==='expenses'?'active':''}" data-v="expenses"><b>€</b>Dépenses</button><button class="tab ${view==='history'?'active':''}" data-v="history"><b>▥</b>Historique</button><button class="tab ${view==='profile'?'active':''}" data-v="profile"><b>◉</b>Profil</button></nav></div>`;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{view=b.dataset.v;renderShell()});({home:homeView,photo:photoView,expenses:expensesView,history:historyView,profile:profileView}[view]||homeView)()}
function myExpenses(){return state.expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt))}
function sums(){const d=new Date(),t=today(),mk=ym(d),start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));start.setHours(0,0,0,0);let day=0,week=0,month=0;for(const x of state.expenses){const xd=new Date(x.date+'T12:00:00');if(x.date===t)day+=+x.amount;if(xd>=start)week+=+x.amount;if(x.date.startsWith(mk))month+=+x.amount}return{day,week,month}}
function homeView(){const p=me(),s=sums(),st=photoStreak(p.phone),fl=totalFlames(p.phone);document.getElementById('main').innerHTML=`<section class="hero"><div class="hello">Bonjour ${esc(p.name)}</div><h1>Ma vie étudiante</h1><div class="metrics"><div class="metric"><small>Aujourd’hui</small><strong>${fmt(s.day)}</strong></div><div class="metric"><small>Cette semaine</small><strong>${fmt(s.week)}</strong></div><div class="metric"><small>Ce mois</small><strong>${fmt(s.month)}</strong></div></div></section><section class="card"><div class="card-title"><h2>🔥 Motivation</h2><button class="btn btn-soft" id="goPhoto">Photo du jour</button></div><div class="streakbar"><div class="streakbox"><small>Série avec photo</small><strong>🔥 ${st} jour${st>1?'s':''}</strong></div><div class="streakbox blue"><small>Flammes reçues</small><strong>🔥 ${fl}</strong></div></div></section>${messagesBlock()}<section class="card"><div class="card-title"><h2>Dépenses récentes</h2><button class="btn btn-blue" id="addExp">+ Ajouter</button></div><div class="expense-list">${expenseRows(myExpenses().slice(0,5))||'<div class="empty">Aucune dépense.</div>'}</div></section>`;document.getElementById('goPhoto').onclick=()=>{view='photo';renderShell()};document.getElementById('addExp').onclick=expenseModal;wireMessages()}
function messagesBlock(){const p=me(),m=state.messages[today()]||{};return `<section class="card"><div class="card-title"><h2>Messages du jour</h2><span class="sub">Aujourd’hui</span></div><div class="message-grid"><div class="msg"><h3>🎓 Étudiant</h3><div class="text">${esc(m.student||'Aucun message.')}</div><div class="meta">Visible par les parents</div>${p.role==='student'?'<button class="btn btn-soft btn-block" data-msg="student">Écrire / modifier</button>':''}</div><div class="msg"><h3>👪 Parents</h3><div class="text">${esc(m.parent||'Aucun message.')}</div><div class="meta">Visible par l’étudiant</div>${p.role==='parent'?'<button class="btn btn-soft btn-block" data-msg="parent">Écrire / modifier</button>':''}</div></div></section>`}
function wireMessages(){document.querySelectorAll('[data-msg]').forEach(b=>b.onclick=()=>messageModal(b.dataset.msg))}
function photoView(){const p=me(),mine=getPhoto(p.phone,today()),visible=visibleTodayPhotos();document.getElementById('main').innerHTML=`<section class="card"><div class="card-title"><h2>Photo du jour</h2><span class="sub">Une photo par jour</span></div>${photoCard(mine,true)}<div class="streakbar"><div class="streakbox"><small>Ma série</small><strong>🔥 ${photoStreak(p.phone)} jour${photoStreak(p.phone)>1?'s':''}</strong></div><div class="streakbox blue"><small>Flammes reçues</small><strong>🔥 ${totalFlames(p.phone)}</strong></div></div><button class="btn btn-blue btn-block" id="uploadPhoto" style="margin-top:11px">📷 ${mine?'Remplacer ma photo':'Publier ma photo'}</button><input id="photoInput" class="hidden" type="file" accept="image/*" capture="environment"><div class="privacy-note">${p.role==='student'?'Tu vois les photos du jour de tes parents.':'Tu vois uniquement la photo du jour de ton fils.'}</div></section><section class="card"><div class="card-title"><h2>${p.role==='student'?'Photos des parents':'Photo de mon fils'}</h2></div><div class="family-grid">${visible.length?visible.map(x=>photoCard(x,false)).join(''):'<div class="empty">Pas encore de photo aujourd’hui.</div>'}</div></section>`;document.getElementById('uploadPhoto').onclick=()=>document.getElementById('photoInput').click();document.getElementById('photoInput').onchange=handlePhoto;wireReactions()}
function photoCard(photo,isMine){if(!photo)return `<div class="photo-stage"><div class="photo-empty"><b>📷</b><span>Pas encore de photo aujourd’hui</span></div></div>`;const owner=state.profiles[photo.phone]?.name||'Profil';const counts=reactionCounts(photo.id);return `<div class="family-photo"><div class="photo-stage"><img src="${photo.data}" alt="Photo du jour"><div class="photo-owner">${esc(owner)} · ${dateShort(photo.date)}</div></div>${!isMine?`<div class="cap"><div class="reaction-row">${REACTIONS.map(r=>`<button class="react ${hasReacted(photo.id,r)?'on':''}" data-photo="${photo.id}" data-react="${r}">${r} ${counts[r]||0}</button>`).join('')}</div></div>`:''}</div>`}
function visibleTodayPhotos(){const p=me();return state.photos.filter(ph=>ph.date===today()&&ph.phone!==p.phone&&((p.role==='student'&&state.profiles[ph.phone]?.role==='parent')||(p.role==='parent'&&state.profiles[ph.phone]?.role==='student')))}
function getPhoto(phone,date){return state.photos.find(p=>p.phone===phone&&p.date===date)}
async function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;try{const data=await compressImage(f,1000,.78);const old=getPhoto(me().phone,today());if(old){old.data=data;old.updatedAt=new Date().toISOString()}else state.photos.push({id:(crypto.randomUUID?.()||String(Date.now())),phone:me().phone,date:today(),data,createdAt:new Date().toISOString()});save();toast('Photo du jour enregistrée');photoView()}catch{toast('Impossible de traiter la photo')}}
function compressImage(file,max=1000,q=.78){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const im=new Image();im.onerror=reject;im.onload=()=>{let w=im.width,h=im.height;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);resolve(c.toDataURL('image/jpeg',q))};im.src=fr.result};fr.readAsDataURL(file)})}
function wireReactions(){document.querySelectorAll('[data-react]').forEach(b=>b.onclick=()=>toggleReaction(b.dataset.photo,b.dataset.react))}
function toggleReaction(photoId,reaction){const phone=me().phone;const i=state.reactions.findIndex(r=>r.photoId===photoId&&r.phone===phone&&r.reaction===reaction);if(i>=0)state.reactions.splice(i,1);else state.reactions.push({photoId,phone,reaction,createdAt:new Date().toISOString()});save();photoView()}
function reactionCounts(id){const o={};state.reactions.filter(r=>r.photoId===id).forEach(r=>o[r.reaction]=(o[r.reaction]||0)+1);return o}
function hasReacted(id,r){return state.reactions.some(x=>x.photoId===id&&x.phone===me().phone&&x.reaction===r)}
function totalFlames(phone){const ids=new Set(state.photos.filter(p=>p.phone===phone).map(p=>p.id));return state.reactions.filter(r=>ids.has(r.photoId)&&r.reaction==='🔥').length}
function photoStreak(phone){const dates=[...new Set(state.photos.filter(p=>p.phone===phone).map(p=>p.date))].sort().reverse();if(!dates.length)return 0;let d=new Date(today()+'T12:00:00');const hasToday=dates.includes(today());if(!hasToday){d.setDate(d.getDate()-1);if(!dates.includes(d.toISOString().slice(0,10)))return 0}let n=0;while(dates.includes(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function expensesView(){document.getElementById('main').innerHTML=`<section class="card"><div class="card-title"><h2>Toutes les dépenses</h2><button class="btn btn-blue" id="addExp">+ Ajouter</button></div><div class="expense-list">${expenseRows(myExpenses())||'<div class="empty">Aucune dépense.</div>'}</div></section>`;document.getElementById('addExp').onclick=expenseModal}
function expenseRows(a){return a.map(x=>`<div class="expense"><div class="ico">${CATS[x.category]||'🧾'}</div><div><div class="name">${esc(x.shop||x.category)}</div><div class="meta">${dateShort(x.date)} · ${esc(x.category)}${x.note?' · '+esc(x.note):''}</div></div><div class="amount">${fmt(x.amount)}</div></div>`).join('')}
function historyView(){document.getElementById('main').innerHTML=`<section class="card"><div class="card-title"><h2>Historique mensuel</h2><span class="sub">Touchez un mois</span></div>${monthRows()}<div id="monthDetail"></div></section>`;wireMonths()}
function monthRows(){const m={};state.expenses.forEach(x=>m[x.date.slice(0,7)]=(m[x.date.slice(0,7)]||0)+Number(x.amount));return Object.keys(m).sort().reverse().map(k=>`<div class="month" data-month="${k}"><div><strong>${monthName(k)}</strong><div class="sub">${state.expenses.filter(x=>x.date.startsWith(k)).length} dépense(s)</div></div><div><b>${fmt(m[k])}</b> <span class="chev">›</span></div></div>`).join('')||'<div class="empty">Aucun historique.</div>'}
function wireMonths(){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{const k=b.dataset.month,a=state.expenses.filter(x=>x.date.startsWith(k)).sort((x,y)=>y.date.localeCompare(x.date));document.getElementById('monthDetail').innerHTML=`<div class="card" style="box-shadow:none;border:1px solid var(--line)"><div class="card-title"><h2>${monthName(k)}</h2><span>${fmt(a.reduce((s,x)=>s+Number(x.amount),0))}</span></div><div class="expense-list">${expenseRows(a)}</div></div>`})}
function profileView(){const p=me();document.getElementById('main').innerHTML=`<section class="card"><div class="card-title"><h2>Mon profil</h2></div><div class="profile-line"><span>Prénom</span><strong>${esc(p.name)}</strong></div><div class="profile-line"><span>Numéro</span><strong>${prettyPhone(p.phone)}</strong></div><div class="profile-line"><span>Profil</span><strong>${p.role==='student'?'Étudiant':'Parent'}</strong></div><div class="profile-line"><span>Connexion</span><strong>Mémorisée sur cet appareil</strong></div><button id="pinChange" class="btn btn-soft btn-block" style="margin-top:12px">Modifier mon code PIN</button><button id="logout" class="btn btn-danger btn-block" style="margin-top:8px">Se déconnecter</button></section><section class="card"><div class="card-title"><h2>Photo & motivation</h2></div><div class="profile-line"><span>Série actuelle</span><strong>🔥 ${photoStreak(p.phone)} jour(s)</strong></div><div class="profile-line"><span>Flammes reçues</span><strong>🔥 ${totalFlames(p.phone)}</strong></div></section><div class="privacy-note">Cette version fonctionne immédiatement sur un seul navigateur. Pour synchroniser automatiquement photos, réactions, messages et dépenses entre trois téléphones différents, il faut connecter l'application à une base cloud sécurisée.</div>`;document.getElementById('pinChange').onclick=()=>renderChangePin(false);document.getElementById('logout').onclick=logout}
function expenseModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="back"><div class="modal"><div class="card-title"><h2>Nouvelle dépense</h2><button id="close" class="btn btn-soft">Fermer</button></div><form id="expForm" class="form"><div class="row2"><div class="field"><label>Date</label><input id="edate" type="date" value="${today()}" required></div><div class="field"><label>Montant</label><input id="eamount" inputmode="decimal" placeholder="0,00" required></div></div><div class="field"><label>Commerce</label><input id="eshop" placeholder="Ex. Carrefour"></div><div class="field"><label>Catégorie</label><select id="ecat">${Object.keys(CATS).map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><label>Commentaire</label><input id="enote" placeholder="Optionnel"></div><button class="btn btn-primary btn-block">Enregistrer</button></form></div></div>`);document.getElementById('close').onclick=closeModal;document.getElementById('back').onclick=e=>{if(e.target.id==='back')closeModal()};document.getElementById('expForm').onsubmit=e=>{e.preventDefault();const n=parseFloat(eamount.value.replace(',','.'));if(!n||n<0)return toast('Montant invalide');state.expenses.push({id:crypto.randomUUID?.()||String(Date.now()),date:edate.value,amount:n,shop:eshop.value.trim(),category:ecat.value,note:enote.value.trim(),createdAt:new Date().toISOString()});save();closeModal();toast('Dépense enregistrée');renderShell()}}
function messageModal(kind){const m=state.messages[today()]||{};document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="back"><div class="modal"><div class="card-title"><h2>Message du jour</h2><button id="close" class="btn btn-soft">Fermer</button></div><form id="msgForm" class="form"><div class="field"><label>Votre message</label><textarea id="msg">${esc(m[kind]||'')}</textarea></div><button class="btn btn-primary btn-block">Enregistrer</button></form></div></div>`);document.getElementById('close').onclick=closeModal;document.getElementById('msgForm').onsubmit=e=>{e.preventDefault();state.messages[today()]={...(state.messages[today()]||{}),[kind]:msg.value.trim(),updatedAt:new Date().toISOString()};save();closeModal();toast('Message enregistré');renderShell()}}
function closeModal(){document.querySelector('.modal-backdrop')?.remove()}
function dateShort(s){return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(s+'T12:00:00'))}
function prettyPhone(s){return s.replace(/(\d{2})(?=\d)/g,'$1 ').trim()}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=3').catch(()=>{}))}
app();
